export const ON_LOGGIN = 'onLogin'
export const TEST_ACTION_TYPE_ONE = 'one'
export const TEST_ACTION_TYPE_TWO = 'two'
export const TEST_ACTION_TYPE_THREE = 'three'
export const TEST_ACTION_TYPE_FOUR = 'four'
